name: CI

on: [push, repository_dispatch]

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Visualizer
        uses: actions/checkout@v2
        with:
          path: viz
          ref: standalone
      - name: Checkout Parser
        uses: actions/checkout@v2
        with:
          repository: tcheinen/nand2tetris-hdl-parser
          ref: pyo3
          path: parse
      - name: setup toolchain
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: stable
            override: true
            target: ${{matrix.TARGET}}
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: py-deps
        run: |
          pip install --upgrade pip
          pip install cffi maturin cx_freeze==6.8b3 schemdraw numpy
      - name: py-install
        run: |
          maturin build --manifest-path parse/Cargo.toml --release --interpreter python3.9
          ls parse/target/wheels
          ls parse/target/release
      - name: install built parser
        run: pip install ./parse/target/wheels/nand2tetris_hdl_parser-0.1.0-cp39-none-win_amd64.whl
      - name: build
        run: |
          cd viz
          python3.9 ./setup.py build
      - uses: actions/upload-artifact@v2
        with:
          name: cli.exe
          path: viz/dist